# Use an official Node.js runtime as a parent image
FROM nginx:alpine

# Set the working directory in the container
WORKDIR /app



EXPOSE 443

# Define the command to run the application
CMD ["sh", "script.sh"]