"""adding descritpion to dict

Revision ID: 19b8a393f82d
Revises: e40be09b29a6
Create Date: 2025-11-16 09:59:48.989077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19b8a393f82d'
down_revision = 'e40be09b29a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dictionnaire', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dictionnaire', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
