"""salut

Revision ID: 21c58e2eec28
Revises: 95f007c1f19c
Create Date: 2025-11-20 11:46:03.332716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21c58e2eec28'
down_revision = '95f007c1f19c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(), nullable=True))
        batch_op.drop_column('genre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('language')

    # ### end Alembic commands ###
