"""new content model

Revision ID: 684d134358d3
Revises: 977fe2fc3b6a
Create Date: 2025-11-13 14:45:46.382320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '684d134358d3'
down_revision = '977fe2fc3b6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('content_version', sa.Integer(), nullable=False))
        batch_op.drop_column('contenu')
        batch_op.drop_column('type')
        batch_op.drop_column('order')

    with op.batch_alter_table('terme', schema=None) as batch_op:
        batch_op.drop_column('path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('terme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('contenu', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('content_version')
        batch_op.drop_column('content')

    # ### end Alembic commands ###
