"""empty message

Revision ID: 81313bca15d6
Revises: 
Create Date: 2025-11-13 13:20:06.822177

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '81313bca15d6'
down_revision = None
branch_labels = None
depends_on = None
def generate_id():
    import secrets
    # Generates a 16-character random hexadecimal string
    return secrets.token_hex(8).upper()  # 8 bytes = 16 hex chars

# sa.Column('secret', sa.String(length=16))

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contenu')
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secret', sa.String(length=16)))
        batch_op.alter_column('ctime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('utime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.create_unique_constraint(None, ['secret'])

    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secret', sa.String(length=16)))
        batch_op.alter_column('ctime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('utime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.create_unique_constraint(None, ['secret'])

    with op.batch_alter_table('dictionnaire', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secret', sa.String(length=16)))
        batch_op.create_unique_constraint(None, ['secret'])

    with op.batch_alter_table('dictionnaire_termes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secret', sa.String(length=16)))
        batch_op.create_unique_constraint(None, ['secret'])

    with op.batch_alter_table('ip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secret', sa.String(length=16)))
        batch_op.create_unique_constraint(None, ['secret'])

    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secret', sa.String(length=16)))
        batch_op.create_unique_constraint(None, ['secret'])

    with op.batch_alter_table('ownership', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secret', sa.String(length=16)))
        batch_op.create_unique_constraint(None, ['secret'])

    with op.batch_alter_table('reaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secret', sa.String(length=16)))
        batch_op.create_unique_constraint(None, ['secret'])

    with op.batch_alter_table('relationship', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secret', sa.String(length=16)))
        batch_op.create_unique_constraint(None, ['secret'])

    with op.batch_alter_table('suggestion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secret', sa.String(length=16)))
        batch_op.create_unique_constraint(None, ['secret'])

    with op.batch_alter_table('terme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secret', sa.String(length=16)))
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'fr'::character varying"))
        batch_op.alter_column('context',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'neutre'::character varying"))
        batch_op.alter_column('ctime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('utime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.create_unique_constraint(None, ['secret'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secret', sa.String(length=16)))
        batch_op.alter_column('ctime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('utime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.create_unique_constraint(None, ['secret'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('utime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('ctime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.drop_column('secret')

    with op.batch_alter_table('terme', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('utime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('ctime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('context',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'neutre'::character varying"))
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'fr'::character varying"))
        batch_op.drop_column('secret')

    with op.batch_alter_table('suggestion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('secret')

    with op.batch_alter_table('relationship', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('secret')

    with op.batch_alter_table('reaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('secret')

    with op.batch_alter_table('ownership', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('secret')

    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('secret')

    with op.batch_alter_table('ip', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('secret')

    with op.batch_alter_table('dictionnaire_termes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('secret')

    with op.batch_alter_table('dictionnaire', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('secret')

    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('utime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('ctime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.drop_column('secret')

    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('utime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('ctime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.drop_column('secret')

    op.create_table('contenu',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('contenu', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('terme_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['terme_id'], ['terme.id'], name='contenu_terme_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='contenu_pkey')
    )
    # ### end Alembic commands ###
