"""salut

Revision ID: 95f007c1f19c
Revises: 
Create Date: 2025-11-20 11:44:15.155913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95f007c1f19c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('terme', schema=None) as batch_op:
        batch_op.drop_column('genre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('terme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.VARCHAR(length=100), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
