"""adding path to terme

Revision ID: 977fe2fc3b6a
Revises: 81313bca15d6
Create Date: 2025-11-13 13:56:13.300094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '977fe2fc3b6a'
down_revision = '81313bca15d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('terme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('terme', schema=None) as batch_op:
        batch_op.drop_column('path')

    # ### end Alembic commands ###
