"""delete content, add version and content to terme directly

Revision ID: a633ebea10ee
Revises: 684d134358d3
Create Date: 2025-11-13 14:54:08.008747

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a633ebea10ee'
down_revision = '684d134358d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content')
    with op.batch_alter_table('terme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('terme', schema=None) as batch_op:
        batch_op.drop_column('content')

    op.create_table('content',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('terme_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ctime', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('utime', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('secret', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content_version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['terme_id'], ['terme.id'], name='content_terme_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='content_pkey'),
    sa.UniqueConstraint('secret', name='content_secret_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
