"""unique temre name

Revision ID: aee471d5e577
Revises: 19b8a393f82d
Create Date: 2025-11-16 10:54:53.905858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aee471d5e577'
down_revision = '19b8a393f82d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('terme', schema=None) as batch_op:
        batch_op.drop_constraint('terme_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('terme', schema=None) as batch_op:
        batch_op.create_unique_constraint('terme_name_key', ['name'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
