"""no unique name dico

Revision ID: e40be09b29a6
Revises: f538d1c1d140
Create Date: 2025-11-13 17:01:49.262381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e40be09b29a6'
down_revision = 'f538d1c1d140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dictionnaire', schema=None) as batch_op:
        batch_op.drop_constraint('dictionnaire_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dictionnaire', schema=None) as batch_op:
        batch_op.create_unique_constraint('dictionnaire_name_key', ['name'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
