"""new version vesrion

Revision ID: f538d1c1d140
Revises: a633ebea10ee
Create Date: 2025-11-13 15:52:43.856144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f538d1c1d140'
down_revision = 'a633ebea10ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('genre', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('version', schema=None) as batch_op:
        batch_op.drop_column('type')
        batch_op.drop_column('genre')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
